apiVersion: rkeprep/v1
kind: Server
metadata:
  name: j64manager-ctrl01
spec:
  hostname: j64manager-ctrl01
  interfaces:
    # Primary
    - name: ens33
      ip: 10.0.4.131
      prefix: 24
      gateway: 10.0.4.1
      dns: ["10.0.1.34", "10.231.1.34"]
      searchDomains: ["dev.kube", "dev.local"]
    # Storage
    - name: ens35
      ip: 172.16.0.101
      prefix: 24
      gateway:
      dns: ["10.0.1.34", "10.231.1.34"]
      searchDomains: ["dev.kube", "dev.local"]
    # Segment1
    - name: ens36
      ip: 1.0.0.131
      prefix: 24
      gateway: 1.0.0.1
      dns: ["1.0.1.34"]
      searchDomains: ["dev.kube", "dev.local"]
  node-taint:
  - "node-role.kubernetes.io/control-plane:NoSchedule"
  node-label:
  - "env=preprod"
  tls-san:
    - j64manager-ctrl01
    - j64manager-ctrl01.dev.kube
    - j64manager-cluster
    - j64manager-cluster.dev.kube
    - 10.0.4.131
  service-cidr: 10.93.0.0/16
  cluster-cidr: 10.243.0.0/16
  cluster-domain: cluster.local
  enable-servicelb: "false"
  kube-apiserver-arg:
    - "audit-log-maxage=15"
  tokenFile: /rke2-node-init/outputs/j64manager-ca-bootstrap-token.txt
  customCA:
    rootCrt: /opt/rke2/stage/certs/dev-certa001-ca-dev-local.crt
    rootKey: /opt/rke2/stage/certs/dev-certa001-ca-dev-local-key.pem
    installToOSTrust: true
  disable:
  - rke2-ingress-nginx
